version: "3.9"
services:
  app:
    container_name: ApiGatewayApplication
    restart: on-failure
    command: java -jar target/ApiGatewayApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8085:8085
    expose:
      - 8085
    volumes:
      - ./:/app/app
    networks:
      - backend

networks:
  backend:
    name: KBE
    external: true
