version: "3.9"
services:
  app:
    container_name: ApiGatewayApplication
    restart: unless-stopped
    build: .
    ports:
      - 8085:8085
    networks:
      - backend

networks:
  backend:
    name: KBE
    external: true
