server:
  port: 8085


#rabbitMQ
queue-names:
  product-service: components.rpc.queue
  user-products: user-products.rpc.queue

routing-keys:
  product-service: components.rpc.key
  user-products: user-products.rpc.key

xchange:
  name: exchange.rpc
