server:
  port: 8085

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672

#rabbitMQ
queue-names:
  product-service: product-service.rpc.queue
  price-service: price-service.rpc.queue
  currency-service: currency-service.rpc.queue

routing-keys:
  product-service: product-service.rpc.key
  price-service: price-service.rpc.key
  currency-service: currency-service.rpc.key

xchange:
  name: exchange.rpc

#keycloak
keycloak:
  auth-server-url: http://localhost:8080/
  public-client: true
  realm: KBE_Authentication
  resource: fruits
  ssl-required: external
  confidential-port: 0
